#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

ENV_OVERRIDE_NAMES=(
  APP_API_PORT
  APP_ENV
  AUTO_LOAD_DEMO_KNOWLEDGE
  BACKEND_HOST
  BACKEND_PORT
  CORS_ORIGINS
  DEEPSEEK_API_KEY
  LLM_API_BASE
  LLM_API_KEY
  LLM_ENABLE_THINKING
  LLM_FALLBACK_API_BASE
  LLM_FALLBACK_API_KEY
  LLM_FALLBACK_ENABLE_THINKING
  LLM_FALLBACK_ENABLED
  LLM_FALLBACK_MAX_TOKENS
  LLM_FALLBACK_MODEL
  LLM_FALLBACK_PROVIDER
  LLM_FALLBACK_SEND_CHAT_TEMPLATE_KWARGS
  LLM_FALLBACK_SEND_THINKING_PARAM
  LLM_FALLBACK_TIMEOUT_SECONDS
  LLM_MAX_TOKENS
  LLM_MODEL
  LLM_PROVIDER
  LLM_SEND_CHAT_TEMPLATE_KWARGS
  LLM_SEND_THINKING_PARAM
  LLM_TIMEOUT_SECONDS
  PYTHON_BIN
  RAG_USE_LLM
  REDIS_URL
)

declare -A ENV_OVERRIDES=()
for name in "${ENV_OVERRIDE_NAMES[@]}"; do
  if [[ "${!name+x}" == "x" ]]; then
    ENV_OVERRIDES["${name}"]="${!name}"
  fi
done

if [[ -f "${ROOT_DIR}/.env" ]]; then
  set -a
  # shellcheck source=/dev/null
  source "${ROOT_DIR}/.env"
  set +a
fi

for name in "${!ENV_OVERRIDES[@]}"; do
  export "${name}=${ENV_OVERRIDES[${name}]}"
done

PYTHON_BIN="${PYTHON_BIN:-${ROOT_DIR}/.venv/bin/python}"
BACKEND_HOST="${BACKEND_HOST:-0.0.0.0}"
BACKEND_PORT="${BACKEND_PORT:-18080}"

export APP_API_PORT="${BACKEND_PORT}"
export RAG_USE_LLM="${RAG_USE_LLM:-true}"
export LLM_API_BASE="${LLM_API_BASE:-http://192.168.27.250:18003/v1}"
export LLM_MODEL="${LLM_MODEL:-Qwen3.6-27B}"
export LLM_API_KEY="${LLM_API_KEY:-qwen-local-key}"
export LLM_TIMEOUT_SECONDS="${LLM_TIMEOUT_SECONDS:-60}"
export LLM_MAX_TOKENS="${LLM_MAX_TOKENS:-512}"
export LLM_SEND_CHAT_TEMPLATE_KWARGS="${LLM_SEND_CHAT_TEMPLATE_KWARGS:-true}"
export LLM_ENABLE_THINKING="${LLM_ENABLE_THINKING:-false}"
export LLM_FALLBACK_ENABLED="${LLM_FALLBACK_ENABLED:-true}"
export LLM_FALLBACK_PROVIDER="${LLM_FALLBACK_PROVIDER:-deepseek}"
export LLM_FALLBACK_API_BASE="${LLM_FALLBACK_API_BASE:-https://api.deepseek.com}"
export LLM_FALLBACK_MODEL="${LLM_FALLBACK_MODEL:-deepseek-v4-flash}"
export LLM_FALLBACK_TIMEOUT_SECONDS="${LLM_FALLBACK_TIMEOUT_SECONDS:-45}"
export LLM_FALLBACK_MAX_TOKENS="${LLM_FALLBACK_MAX_TOKENS:-512}"
export LLM_FALLBACK_SEND_CHAT_TEMPLATE_KWARGS="${LLM_FALLBACK_SEND_CHAT_TEMPLATE_KWARGS:-false}"
export LLM_FALLBACK_SEND_THINKING_PARAM="${LLM_FALLBACK_SEND_THINKING_PARAM:-true}"
export LLM_FALLBACK_ENABLE_THINKING="${LLM_FALLBACK_ENABLE_THINKING:-false}"

cd "${ROOT_DIR}/backend"
exec "${PYTHON_BIN}" -m uvicorn app.main:app --host "${BACKEND_HOST}" --port "${BACKEND_PORT}"
